### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by SDS1234** [MatthiasReumann/webuntis-to-ics-calendar#2]
Traceback (most recent call last):
  File "C:\Users\SDS\Downloads\webuntis-to-ics-calendar-master\main.py", line 120, in <module>
    main()
  File "C:\Users\SDS\Downloads\webuntis-to-ics-calendar-master\main.py", line 106, in main
    config = readTOMLFile(sys.argv[1])
IndexError: list index out of range

**Comment by H4K0N42** [comment]
You have to run: `python main.py config.toml`
